import assert from "node:assert/strict";
import test from "node:test";
import { createWave1Adapter, isParticipantId, validateAggregate, validateEvent, validateHostAcknowledgement, validateHostPreflight, validateHostSession, validatePurge } from "../src/wave1-bridge.js";
import { initialWave1MeasurementState, reduceWave1MeasurementState } from "../src/wave1-ledger.js";
import { getWave1Scenario, initialWave1ReplayViewState, reduceWave1ReplayViewState, wave1FixtureRequest, wave1TaskGroup } from "../src/wave1-replay.js";

const fixtureRequest = wave1FixtureRequest();
const fixture = { ...fixtureRequest, verified: true, build_verified: true };
const retention = { status: "encrypted_local", purge_status: "available" };
const preflight = { capture_mode: "host_authoritative", countable: true, fixture, retention, build: { git_sha: "a".repeat(40), dirty: false } };
const session = { capture_mode: "host_authoritative", countable: true, participant_id: "P01", session_namespace: "wave1-12345678", fixture, retention };
const aggregate = { schema: "spark.proofline.validation.aggregate.v1", event_count: 8, task_counts: [{ task_id: "proofline-1", count: 3 }], outcome_counts: [{ outcome: "success", count: 3 }], hint_count: 1, abandonment_count: 1, first_activity_ms: 67, retention, download_ready: true };
const purge = { purged: true, next_session_namespace: "wave1-87654321", retention: { status: "crypto_erased", purge_status: "purged" } };

test("all five rich rehearsal task states remain accessible", () => { assert.equal(wave1TaskGroup.tasks.length, 5); const repo = getWave1Scenario("repo-brief"); const change = getWave1Scenario("completed-change"); const failed = getWave1Scenario("failed-validation"); const approval = getWave1Scenario("pending-approval"); const usage = getWave1Scenario("partial-usage"); assert.match(repo.citation.source, /:\d+$/); assert.equal(change.files.length, 2); assert.equal(change.validation, "Passed fixture validation"); assert.match(failed.failureCommand, /^fixture validate/); assert.equal(failed.choices.length, 3); assert.match(approval.policy, /Approve fixture-only/i); assert.deepEqual(usage.sourceReportedTokens, { input: 18742, output: 4396 }); assert.equal(usage.pricingState, "unavailable"); });
test("visible replay state remains display-only and creates no telemetry identity", () => { let state = initialWave1ReplayViewState; for (const action of [{ type: "start" }, { type: "open-evidence" }, { type: "open-change" }, { type: "recover", choice: "Restore simulated checkpoint" }, { type: "decide", decision: "approve" }, { type: "usage" }]) state = reduceWave1ReplayViewState(state, action); assert.equal(state.openedRepoEvidence, true); assert.equal(state.openedDiff, true); assert.equal(state.recoveryChoice, "Restore simulated checkpoint"); assert.equal(state.approvalDecision, "approve"); assert.equal(state.usageViewed, true); assert.doesNotMatch(JSON.stringify(state), /event_id|timestamp|occurred_at|sequence|session/i); });
test("browser adapter fails closed and is non-countable without a host", async () => { const adapter = createWave1Adapter({ hostAvailable: false }); assert.equal(adapter.kind, "browser"); assert.equal((await adapter.preflight(fixtureRequest)).countable, false); assert.equal((await adapter.startSession({ participantId: "P01", fixture: fixtureRequest })).countable, false); assert.equal((await adapter.appendEvent({ event_type: "task_outcome" })).acknowledged, false); assert.equal((await adapter.previewAggregate()).event_count, 0); assert.equal((await adapter.purgeSession()).purged, false); });
test("adapter uses exact snake_case host DTO wrappers", async () => { const calls = []; const invoke = async (command, args) => { calls.push({ command, args }); if (command === "wave1_preflight") return preflight; if (command === "wave1_start_session") return session; if (command === "wave1_append_event") return { acknowledged: true, event_type: args.event.event_type, latency_ms: args.event.event_type === "activity_rendered" ? 67 : undefined }; if (command === "wave1_preview_aggregate") return aggregate; return purge; }; const adapter = createWave1Adapter({ invoke }); await adapter.preflight(fixtureRequest); await adapter.startSession({ participantId: "P01", fixture: fixtureRequest }); await adapter.appendEvent({ event_type: "run_submitted", participant_id: "P01", task_id: "proofline-1", outcome: "success", capture_mode: "host_authoritative" }); await adapter.previewAggregate({ download: true }); await adapter.purgeSession(); assert.deepEqual(calls, [{ command: "wave1_preflight", args: { fixture: fixtureRequest } }, { command: "wave1_start_session", args: { participant_id: "P01", fixture: fixtureRequest } }, { command: "wave1_append_event", args: { event: { event_type: "run_submitted", participant_id: "P01", task_id: "proofline-1", outcome: "success", capture_mode: "host_authoritative" } } }, { command: "wave1_preview_aggregate", args: { download: true } }, { command: "wave1_purge_session", args: { confirm: true } }]); });
test("host validators accept exact reports and reject fixture content or unsupported events", () => { assert.deepEqual(validateHostPreflight(preflight), preflight); assert.deepEqual(validateHostSession(session, "P01"), session); assert.deepEqual(validateHostAcknowledgement({ acknowledged: true, event_type: "activity_rendered", latency_ms: 67 }), { acknowledged: true, event_type: "activity_rendered", latency_ms: 67 }); assert.deepEqual(validateAggregate(aggregate), aggregate); assert.deepEqual(validatePurge(purge), purge); assert.equal(isParticipantId("P01"), true); assert.equal(isParticipantId("P00"), false); assert.deepEqual(validateEvent({ event_type: "task_outcome", participant_id: "P01", task_id: "proofline-3", outcome: "hinted", capture_mode: "host_authoritative" }), { event_type: "task_outcome", participant_id: "P01", task_id: "proofline-3", outcome: "hinted", capture_mode: "host_authoritative" }); assert.throws(() => validateEvent({ event_type: "recovery_selected", participant_id: "P01", task_id: "proofline-3", outcome: "success", capture_mode: "host_authoritative" }), /allowlisted/i); assert.throws(() => validateEvent({ event_type: "task_outcome", participant_id: "P01", task_id: "proofline-3", outcome: "success", capture_mode: "host_authoritative", prompt: "fixture evidence" }), /allowlisted/i); assert.throws(() => validateAggregate({ ...aggregate, paths: ["fixture/usage/history.rs"] }), /aggregate-only/i); });
test("measurement reducer receives host namespace and purge report without making authority values", () => { let state = reduceWave1MeasurementState(initialWave1MeasurementState, { type: "preflight", capture: preflight, fixture, retention }); state = reduceWave1MeasurementState(state, { type: "session", capture: session, fixture, retention, sessionNamespace: session.session_namespace }); state = reduceWave1MeasurementState(state, { type: "ack", eventType: "activity_rendered:success", acknowledgement: { acknowledged: true, event_type: "activity_rendered", latency_ms: 67 } }); assert.equal(state.sessionNamespace, session.session_namespace); assert.equal(state.acknowledgements["activity_rendered:success"].latency_ms, 67); const afterPurge = reduceWave1MeasurementState(state, { type: "purged", capture: { ...preflight, retention: purge.retention }, retention: purge.retention, nextSessionNamespace: purge.next_session_namespace }); assert.equal(afterPurge.sessionNamespace, null); assert.equal(afterPurge.purged, true); });
